### ISSUE TITLE
[Ai Shyoujo] - Rendered Screenshots crashes the entire computer.

### ISSUE THREAD

**Issue by aGKamui** [IllusionMods/BepisPlugins#110]
This was a issue I opened a while back, but then suddenly it stopped so It was okay.
Then its happening again, and this can be extremely damaging to the computer shutting down like this I've never seen anything like it in anything.

Its simple, you click F11 your computer instantly shuts down.

I couldn't get footage, now it happened 6 times in a row and well I guess I can't take alpha pictures anymore.

Before you say computer is bad and thats the cause:
i7 6700K
GTX 1080Ti
16 Gigs of Ram

Video footage of it happening.
(Also I literally just clicked F11 i didn't do anything else.)
[Video](https://www.youtube.com/watch?v=fZMDMaFQh64)

How to reproduce:
To reproduce you literally open Studio, add a character change it a bit click F11.

Expected behavior:
Not shutdown my computer.

**Comment by ManlyMarco** [comment]
It looks like a standard nvidia driver crash caused by not enough free memory. Lower your screenshot downsampling factor or resolution and keep an eye on memory usage in task manager.

This is not something we can do much about since it's not a bug in the code - the process is inherently very resource intensive. Reducing memory usage is theoretically possible but difficult and no one is willing to tackle it at the moment.

**Comment by aGKamui** [comment]
Ohhh, I didn't change the upsampling but it was set as 4.
Didn't notice, what do you recommend?

**Comment by ManlyMarco** [comment]
2 in most cases, higher is getting into placebo area. Sometimes you might need to do 1 if some special effects don't look right.
