### ISSUE TITLE
[HS2/AI] - [Studio Scene Save/Load extResolve-intResolve Mismatch]

### ISSUE THREAD

**Issue by hooh-hooah** [IllusionMods/BepisPlugins#117]
- BepinEx 5.3.0
- Latest Better Repack
- Latest BepisPlugins r15.4

## Describe the bug
* When I save my studio items, it does not save the item's resolved ID.
* Apparently, when I'm saving/loading my scene internal resolver didn't save the correct slot.
* Because of that, The Scene is trying to load invalid studio items from an invalid category.
* Ending up spawning spheres when it loads when scene loading is completed.

<img width="1600" alt="StudioNEOV2_icCri9hpDB" src="https://user-images.githubusercontent.com/55322444/90303395-9dd54480-dee8-11ea-8a27-1a8ceffb7c0b.png">
<img width="1616" alt="dnSpy_JSvj3lCNeP" src="https://user-images.githubusercontent.com/55322444/90303396-9f9f0800-dee8-11ea-854a-40a86f5529ee.png">
<img width="1600" alt="StudioNEOV2_68BiM5Ap0S" src="https://user-images.githubusercontent.com/55322444/90303555-ca3d9080-dee9-11ea-9be3-6c7b8afa90be.png">

### Run-Time
* Get Mod (DM me for this one)
* Save Scene
* Load Scene
### Mod-Packing
Put more than 2 categories in sideloader mods.

## Additional Informations
**Studio Items Structure**
![image](https://user-images.githubusercontent.com/55322444/90303618-59e33f00-deea-11ea-95a7-736c267bb451.png)

**Additional Note**
It seems to add maps and studio item list affects map no resolve error - I need to find more information about this one.

## Expected behavior
* Save/Load Scene Correctly
* intResolve and extResolve must match

![image](https://user-images.githubusercontent.com/55322444/90303464-294ed580-dee9-11ea-92de-edb21473c79c.png)

## Workaround
Split all category files by separated zipmod...

**Example**
* assets.zipmod
* studio_props_category_1.zipmod
* studio_props_category_2.zipmod

![image](https://user-images.githubusercontent.com/55322444/90303735-7e8be680-deeb-11ea-83e7-d7e49b891446.png)

It fixes the problem temporarily but I don't think this would be a permanent solution (;-;)

**Comment by hooh-hooah** [comment]
Additional Information Goes here:
* It seems only first of category in the zipmod solved right
* It seems there is no value that can distinguish category and slot number when resolving intResolve in "ResolveStudioObject" (my personal opinion)

**Comment by hooh-hooah** [comment]
Okay that works I'll try to make pull request.

**Comment by DeathWeasel1337** [comment]
Sideloader for studio items, maps, lights, and others expects every ID to be unique. Animations can have duplicate IDs because they are resolved based on the GUID, ID, group, and category. Other items types are resolved based on GUID and ID only, meaning duplicate IDs in separate groups and categories will cause conflicts. Modify your list files and ensure that every ID is unique to prevent this problem.

Considering the amount of time it would take to implement, this does not seem like a worthwhile use of time. Especially so considering there are over 500 studio mods between KK and AI/HS2, none of which have any problems, and even more so considering you only need to modify your list files to prevent any problems.
