### ISSUE TITLE
[HS2] - [Long MOD ID error]

### ISSUE THREAD

**Issue by mikimoe** [IllusionMods/BepisPlugins#123]
- Game: HS2, AI
- An old mod I have use 9-digit id. After update sideloader to r16 I found it broken. If I put an ID below 100mil, like 99999999, everything is OK.
In version r15, everything is OK. 
- I don't know how the latest sideloader change its method. However, it might not work.

**Comment by ManlyMarco** [comment]
IDs have to be below 100,000,000. The limit was always the same, since the first releases. It is listed in the readme here https://github.com/IllusionMods/BepisPlugins/wiki/1-Introduction-to-zipmod-format#warnings

To fix this you have to change your IDs, this is not a bug in sideloader. Old versions might have broken silently or your IDs might have not conflicted by pure chance.
