### ISSUE TITLE
[KK] - [Capture resolution limit more than 16k]

### ISSUE THREAD

**Issue by lgh5509** [IllusionMods/BepisPlugins#172]
hello.

is the capture resolution limit can be higher than 16k?

to capture scene in more and more high quality, 16k is not enough.

i want really really capture more higher quality.

and thank you for this wonderful and fantastic genius plugin !

i wish your happy and nice day !

**Comment by ManlyMarco** [comment]
Hello!

Unity engine used in KK cannot handle textures larger than 16k, so it's impossible without tiling (take multiple screenshots and photoshop them together).

You can try getting nvidia ansel to work since it can take screenshots way above 16k, but that would require using KKS and an nvidia GPU.
