### ISSUE TITLE
[AI Girls] - [Ambient occlusion doesn't seem to work in Screencap]

### ISSUE THREAD

**Issue by steamb23** [IllusionMods/BepisPlugins#85]
![20191118040719799](https://user-images.githubusercontent.com/6805899/69012436-1d190480-09b9-11ea-8088-90fea5eaddb6.png)
Vanilla
![AI_2019-11-18-04-07-23-293](https://user-images.githubusercontent.com/6805899/69012435-1d190480-09b9-11ea-932a-7e67999e61a6.png)
Screencap

Because the ambient occlusion effect is insignificant or not applied, the brightness of some objects is exaggerated.

It happens in studio as well as the main game.

I used the [r12.4](https://github.com/IllusionMods/BepisPlugins/releases/tag/r12.4) version.

**Comment by ManlyMarco** [comment]
AO now works when not using the downscaling function, no proper fix yet though.

**Comment by BlueGirl91** [comment]
AO doesn't work properly on higher resolutions than the normal setting. It produces strange shadow lines, which get more pronounced the higher the resolution. No upsampling involved.

![AI_2020-02-24-12-16-14-903](https://user-images.githubusercontent.com/61420096/75159303-26341300-5718-11ea-9cb2-4c5b6d2b9bf3.jpg)

**Comment by ManlyMarco** [comment]
Yes, that's why it was completely disabled before. There's no proper fix for this so far.

**Comment by ShikiSuen** [comment]
@BlueGirl91 That issue is because the generated AO data does not follow the upsample settings made by the screenshot plugin.

**Comment by ShikiSuen** [comment]
I removed my previous reply.

I found that this issue can happen even if not using upsampling, as long as your capture resolution is high enough. My case is 9102x5120

**Comment by ShikiSuen** [comment]
One doesn't even need to capture a screenshot to see this issue lively in the game.
![AI_2020-04-09-01-48-37-261](https://user-images.githubusercontent.com/3164826/78811073-4720a100-7a04-11ea-9641-4ee3d3771acd.png)

**Comment by ManlyMarco** [comment]
This is at least partially fixed already. The fix is not released yet, you can compile the plugin from source before a proper release is made.

**Comment by ShikiSuen** [comment]
@ManlyMarco What compiling tools are you using? I saw Visual Studio Community only has 32bit version.

**Comment by ManlyMarco** [comment]
Visual Studio Community 2019 https://visualstudio.microsoft.com/vs/community/
It doesn't matter, it doesn't need to be 64bit.

**Comment by ManlyMarco** [comment]
I believe this is fixed, so I'm closing the issue.

Is this issue is still present, then please make sure you are using the latest build to test, and reopen this issue with an explanation of what exactly is still wrong.

**Comment by ShikiSuen** [comment]
Maybe this issue is only due to the poor shadow rendering methods applied through chara-light.
Studio Neo v2 is bad at keeping rendered shadow quality of charalight shadows.

Today I tried a new methods and found that it can make the Bepis ScreenShot Plugin output the best shadow it can.
Requirements:

1. Disable the shadow of chara-light.
2. Turn the brightness of chara-light to minimum.
3. Tweak everything to make sure that every object is not a light-source (except real things like fire, lightbulb, etc.)
4. Add independent light sources. If one light source cannot achieve sufficient brightness with its max brightness setting, please duplicate this light source to make the lights overlapped together.

This is my test result, using only one light source (actually 3 identical light source to double the brightness):
![image](https://user-images.githubusercontent.com/3164826/104115025-22b87300-534e-11eb-95c8-726871955348.png)
